x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

  clusterConstraints:
    k8sVersion: ">=0.0.1" # TODO: verify

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: True

  images: # TODO: configure all requried images
    '':  # Primary image has no name.
      properties:
        image.repo:
          type: REPO_WITH_REGISTRY
        image.tag:
          type: TAG

  deployerServiceAccount:
    description: Creates app resources, including Webhooks and ClusterRoleBindings.
    roles:
      - type: ClusterRole
        rulesType: CUSTOM
        rules:
          - apiGroups:
              - 'rbac.authorization.k8s.io'
            resources:
              - 'clusterroles'
              - 'clusterrolebindings'
            verbs:
              - '*'
          - apiGroups:
              - 'apiextensions.k8s.io'
            resources:
              - 'customresourcedefinitions'
            verbs:
              - '*'
          - apiGroups:
              - 'admissionregistration.k8s.io'
            resources:
              - 'mutatingwebhookconfigurations'
              - 'validatingwebhookconfigurations'
            verbs:
              - '*'
          - apiGroups:
              - ''
            resources:
              - 'namespaces'
            verbs:
              - 'create'
              - 'list'
              - 'update'
              - 'patch'

properties: # TODO: populate with required values as we go forward
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  logLevel:
    type: string
    title: Log level of Nifi
    description: Level of logs generated by Nifi
    default: INFO
    enum:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG
    - TRACE

required:
- name
- namespace