schema.yaml
x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

  clusterConstraints:
    k8sVersion: ">=1.18.0" # TODO: verify

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      A regular update.
    releaseTypes:
      - Feature
    recommended: True

  images: # TODO: configure all requried images
    '':  # Primary image has no name.
      properties:
        image:
          type: FULL
    nifikop:
      properties:
        nifikop.image:
          type: FULL

  deployerServiceAccount:
    description:
      Creates all app resources.
    roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules: # TODO: come up with a minimal set of roles
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - '*'

properties: # TODO: populate with required values as we go forward
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  logLevel:
    type: string
    title: Log level of Nifi
    description: Level of logs generated by Nifi
    default: INFO
    enum:
    - CRITICAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG
    - TRACE

required:
- name
- namespace