apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIpAddressName }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-cluster
      port:
        number: 8443
