{{- /* https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer */}}
{{- /* https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs */}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpAddressName }}
    networking.gke.io/managed-certificates: {{ .Release.Name }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-cluster
      port:
        number: 8443
{{- end }}
