image:
  repo: eu.gcr.io/prj-cogniflare-marketpl-public/apache/nifi
  tag: 1.20.0

dnsName: test.nifikop.calleido.io # whitelisted in Nifi cluster

ingress:
  enabled: true
  staticIpAddressName: nifikop # Google Cloud Static External IP Address Name

initialAdminUsers:
  - identity: michalkeder@cogniflare.io
    name: michal
  - identity: lukasz.borawski@cogniflare.io
    name: lukasz
  - identity: jakub@cogniflare.io
    name: jakub

oidc: # Google Cloud OAuth 2.0 Client ID for Web Application
  discoveryUrl: https://accounts.google.com/.well-known/openid-configuration
  clientId: 229459469551-7q6uunqocmn9juhg33jcg4vvpcsqf3ug.apps.googleusercontent.com
  secret: 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

nifiSensitivePropsKey: thisIsABadSensitiveKeyPassword # https://nifi.apache.org/docs/nifi-docs/html/administration-guide.html#security_properties

nifiNodes: 1

calleido-deps:
  cert-manager:
    installCRDs: false
    image:
      repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-controller
      tag: v1.10.1
    extraArgs:
      - --namespace=calleido
    replicaCount: 1
    global:
      leaderElection:
        namespace: calleido
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 100m
        memory: 64Mi
    webhook:
      resources:
        limits:
          cpu: 50m
          memory: 32Mi
        requests:
          cpu: 50m
          memory: 32Mi
      image:
        repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-webhook
        tag: v1.10.1
    cainjector:
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 100m
          memory: 64Mi
      image:
        repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-cainjector
        tag: v1.10.1
    startupapicheck:
      enabled: false

  nifikop:
    image:
      repository: eu.gcr.io/prj-cogniflare-marketpl-public/nifikop/nifikop
      tag: 1.0.0-cogniflare0
    namespaces:
      - calleido
    logLevel: Debug
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  zookeeper:
    image:
      registry: eu.gcr.io
      repository: prj-cogniflare-marketpl-public/zookeeper/zookeeper
      tag: 3.8.0-debian-11-r56
    persistence:
      storageClass: standard-rwo
      size: 8Gi
    networkPolicy:
      enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
