apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "Cogniflare", "product_id": "NiFi", "partner_name": "Cogniflare"}'
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  descriptor:
    type: NiFi
    version: 1.18.0
    description: |-
      Apache NiFi supports powerful and scalable directed graphs of data routing, transformation, and system mediation logic.
    maintainers:
    - name: Cogniflare
      url: https://www.cogniflare.io/
    links:
    - description: Getting Started
      url: https://nifi.apache.org/docs/nifi-docs/html/getting-started.html
    notes: |-
      Explore all Cogniflare services [here](https://www.cogniflare.io/cogniflare-products/).
  info:
  - name: Application Namespace
    value: {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  componentKinds:
  - group: ''
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: networking.k8s.io
    kind: IngressClass
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition