templates:
  resources: &autopilot-resources
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
  certManagerResources: &cert-manager-resources
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

cert-manager:
  installCRDs: false
  image:
    repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-controller
    tag: v1.10.1

  global:
    leaderElection:
      namespace: calleido
  resources: *cert-manager-resources
  webhook:
    resources: *cert-manager-resources
    image:
      repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-webhook
      tag: v1.10.1
  cainjector:
    resources: *cert-manager-resources
    image:
      repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-cainjector
      tag: v1.10.1
  startupapicheck:
    resources: *cert-manager-resources
    image:
      repository: eu.gcr.io/prj-cogniflare-marketpl-public/cert-manager/cert-manager-ctl
      tag: v1.10.1

external-dns:
  provider: google
  policy: sync
  txtOwnerId: nifikop
  sources:
    - ingress
  extraArgs:
    - --domain-filter=nifikop.calleido.io
  serviceAccount:
    annotations:
      iam.gke.io/gcp-service-account: external-dns-sa@prj-d-sandbox-364708.iam.gserviceaccount.com
  resources: *autopilot-resources

ingress-nginx:
  controller:
    resources: *autopilot-resources
    admissionWebhooks:
      createSecretJob:
        resources: *autopilot-resources
      patchWebhookJob:
        resources: *autopilot-resources

kube-prometheus-stack:
  coreDns:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeProxy:
    enabled: false
  kubeScheduler:
    enabled: false
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  defaultRules:
    create: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
  prometheusOperator:
    resources: *autopilot-resources
    admissionWebhooks:
      createSecretJob:
        resources: *autopilot-resources
      patch:
        resources: *autopilot-resources

nifikop:
  image:
    repository: eu.gcr.io/prj-cogniflare-marketpl-public/nifikop/nifikop
    tag: 1.0.0-cogniflare0
  namespaces:
    - calleido
  logLevel: Debug
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

prometheus-adapter:
  rules:
    default: true
  prometheus:
    url: http://prometheus-operated.calleido.svc
  resources: *autopilot-resources

zookeeper:
  image:
    registry: eu.gcr.io
    repository: prj-cogniflare-marketpl-public/zookeeper/zookeeper
    tag: 3.8.0-debian-11-r56
  global:
    storageClass: standard-rwo
  networkPolicy:
    enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
