templates:
  resources: &autopilot-resources
    limits:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
    requests:
      cpu: 250m
      ephemeral-storage: 1Gi
      memory: 512Mi
  certManagerResources: &cert-manager-resources
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
